version: 2.1

jobs:
  build-upload-staging:
    docker:
      - image: docker:19.03.13
    environment:
      IMAGE_NAME: bayu3490/bizhub-website
    working_directory: /app
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Generate Docker Image Name
          command: |
            echo 'export VERSION=${CIRCLE_SHA1:0:4}' >> $BASH_ENV
            source $BASH_ENV
            echo 'export IMAGE_NAME=${IMAGE_NAME}:${CIRCLE_BRANCH}-${VERSION}' >> $BASH_ENV 

      - run:
          name: Build Docker Image
          command: | 
            source $BASH_ENV
            docker build -t $IMAGE_NAME .

      - run:
          name: Run, check, delete Test Docker Container
          command: | 
            source $BASH_ENV
            docker run -d --rm $IMAGE_NAME
            docker ps -a
            docker stop $(docker ps -aq)

      - run:
          name: Authentication to Container Registry
          command: echo $access_token | docker login --username bayu3490 --password-stdin

      - run:
          name: Pushing Docker Image to Container Registry
          command: | 
            source $BASH_ENV
            docker push $IMAGE_NAME
            echo $IMAGE_NAME

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-upload-staging:
          context: weeber-context
          filters:
            branches:
              only: master
      - build-upload-staging:
          context: weeber-context
          filters:
            branches:
              only: cicd